# Generated by Django 3.2.4 on 2024-11-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('TShirts', 'T-Shirts'), ('Shirts', 'Shirts'), ('Sweaters', 'Sweaters'), ('Jeans', 'Jeans'), ('Jackets', 'Jackets'), ('Shoes', 'Shoes')], max_length=30)),
                ('title', models.CharField(default='Untitled', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ForWoman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('TShirts', 'T-Shirts'), ('Shirts', 'Shirts'), ('Sweaters', 'Sweaters'), ('Jeans', 'Jeans'), ('Jackets', 'Jackets'), ('Shoes', 'Shoes')], max_length=30)),
                ('title', models.CharField(default='Untitled', max_length=128)),
            ],
        ),
    ]
